# Generated by Django 5.1 on 2024-08-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slugS",
            field=models.SlugField(default=""),
        ),
    ]
