# Generated by Django 5.1 on 2024-08-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_slugs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="slugS",
            new_name="slug",
        ),
    ]
