# Generated by Django 5.1 on 2024-08-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_rename_slugs_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
