# Generated by Django 5.1 on 2024-08-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
