# Generated by Django 5.1 on 2024-08-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_alter_course_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(to="courses.category"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
    ]
