# Generated by Django 5.1 on 2024-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_uploadmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="imageUrl",
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(default="", upload_to="images"),
        ),
    ]
