# Generated by Django 5.1 on 2024-10-12 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_remove_course_imageurl_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
